apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-i0wj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0004-tenant/tkrw-pr712-0075-0004-app/devfile-sample-i0wj@sha256:97e5ad2e5402d1e683baf0e99111eac6a99c3febcfed28f0abeb9b25d87ee1ef
        name: my-nodejs
        resources: {}
status: {}
